# Generated by Django 4.2 on 2024-12-08 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Что нужно сделать', max_length=255)),
                ('time', models.TimeField(help_text='Время выполнения привычки')),
                ('place', models.CharField(help_text='Где выполняется привычка', max_length=255)),
                ('is_pleasant', models.BooleanField(default=False, help_text='Признак приятной привычки')),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Частота выполнения (в днях)')),
                ('reward', models.CharField(blank=True, help_text='Вознаграждение', max_length=255, null=True)),
                ('execution_time', models.PositiveIntegerField(help_text='Время выполнения в минутах')),
                ('is_public', models.BooleanField(default=False, help_text='Публичность привычки')),
                ('linked_habit', models.OneToOneField(blank=True, help_text='Связанная привычка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
