# Generated by Django 4.2 on 2024-12-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="execution_time",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="linked_habit",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="time",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="user",
        ),
        migrations.AddField(
            model_name="habit",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Опубликовать для общего доступа",
                verbose_name="Общий доступ",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="lead_time",
            field=models.IntegerField(
                default=1,
                help_text="Укажите предположительное время выполнения привычки в минутах",
                verbose_name="Время выполнения",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Выбирите связанную приятную привычку",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="rhythm",
            field=models.CharField(
                choices=[
                    ("every day", "каждый день"),
                    ("every other day", "чере день"),
                    ("every three days", "раз в 3 дня"),
                    ("every four days", "раз в 4 дня"),
                    ("every five days", "раз в 5 дней"),
                    ("every six days", "ра в 6 дней"),
                    ("every weak", "раз в неделю"),
                ],
                default="every day",
                help_text="Выберите переодичностьт выполнения привычки",
                max_length=16,
                verbose_name="Переодичность выполнения",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Выберете дату и время начала привычки",
                null=True,
                verbose_name="Время начала выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                help_text="Опишите действие вашей привычки",
                max_length=300,
                verbose_name="Действие привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Привычка является приятной",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True,
                help_text="Укажите место выполнения привычки",
                max_length=100,
                null=True,
                verbose_name="Место выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Укажите вознаграждение",
                max_length=300,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
