# Generated by Django 4.2 on 2024-12-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_groups_alter_user_user_permissions"),
        ("habits", "0002_remove_habit_execution_time_remove_habit_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите связанную приятную привычку",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="rhythm",
            field=models.CharField(
                choices=[
                    ("every day", "каждый день"),
                    ("every other day", "через день"),
                    ("every three days", "раз в 3 дня"),
                    ("every four days", "раз в 4 дня"),
                    ("every five days", "раз в 5 дней"),
                    ("every six days", "раз в 6 дней"),
                    ("every week", "раз в неделю"),
                ],
                default="every day",
                help_text="Выберите периодичность выполнения привычки",
                max_length=16,
                verbose_name="Периодичность выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Выберите дату и время начала привычки",
                null=True,
                verbose_name="Время начала выполнения привычки",
            ),
        ),
    ]
